// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huhohqtsmhtmuazfrqve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1aG9ocXRzbWh0bXVhemZycXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDc0OTIsImV4cCI6MjA1ODIyMzQ5Mn0.xnXRfh9nXMGtgQnnXaJT_5u0-5oagJJ3spfAwZZvg_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);